source 'https://rubygems.org'


gem 'json', '1.8.2'
gem 'xamarin-test-cloud', '2.0.0.pre5'
gem 'cucumber', '~> 2.0.0'
gem 'calabash-android', '0.7.4.pre1'
#gem 'calabash-android', path: '/Users/tobias/xamarin/calabash-android/ruby-gem'
